project_id = "asxcbnkpflgecqreegdd"

[functions.migrate-legacy-keys]
verify_jwt = false

[functions.secure-notification-settings]
verify_jwt = false

[functions.trading-bot]
verify_jwt = true

[functions.daily-retraining]
verify_jwt = true

[functions.security-audit]
verify_jwt = true

[functions.live-trading-engine]
verify_jwt = true

[functions.enhanced-ml-engine]
verify_jwt = true

[functions.market-data-engine]
verify_jwt = false

[functions.notification-engine]
verify_jwt = false