-- =============================================================================
-- PHASE 2 TRADING SAFETY: Kill Switch, Order Idempotency, Risk Constraints
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. GLOBAL KILL SWITCH: Add is_paused to bot_config
--    is_paused = true  → all trading engines must refuse to place orders
--    paused_at         → timestamp when the kill switch was activated
--    paused_reason     → human-readable reason (e.g., 'DAILY_LOSS_LIMIT', 'MANUAL')
-- ---------------------------------------------------------------------------
ALTER TABLE public.bot_config
  ADD COLUMN IF NOT EXISTS is_paused         BOOLEAN   NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS paused_at         TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS paused_reason     TEXT;

-- Index for fast kill-switch lookups by trading engines
CREATE INDEX IF NOT EXISTS idx_bot_config_user_paused
  ON public.bot_config (user_id, is_paused);

-- ---------------------------------------------------------------------------
-- 2. ORDER IDEMPOTENCY: Add client_order_id to executed_trades
--    A UUID generated by the caller before the Kraken API call is stored here.
--    A UNIQUE constraint on (user_id, client_order_id) prevents duplicate
--    order insertions even if the edge function retries after a timeout.
-- ---------------------------------------------------------------------------
ALTER TABLE public.executed_trades
  ADD COLUMN IF NOT EXISTS client_order_id UUID;

-- Unique constraint: one DB row per client-generated order UUID per user
ALTER TABLE public.executed_trades
  DROP CONSTRAINT IF EXISTS uq_executed_trades_client_order_id;

ALTER TABLE public.executed_trades
  ADD CONSTRAINT uq_executed_trades_client_order_id
  UNIQUE (user_id, client_order_id);

-- Index for duplicate-check lookups
CREATE INDEX IF NOT EXISTS idx_executed_trades_client_order_id
  ON public.executed_trades (user_id, client_order_id)
  WHERE client_order_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- 3. MANDATORY STOP-LOSS: Add stop_loss_pct and take_profit_pct to risk_settings
--    These are the percentage-based defaults used by the RiskManager when no
--    per-order stop-loss is provided. A CHECK constraint enforces that
--    stop_loss_pct is always set to a positive, non-zero value.
-- ---------------------------------------------------------------------------
ALTER TABLE public.risk_settings
  ADD COLUMN IF NOT EXISTS stop_loss_pct     NUMERIC NOT NULL DEFAULT 0.02
    CONSTRAINT chk_stop_loss_pct_positive CHECK (stop_loss_pct > 0 AND stop_loss_pct <= 0.50),
  ADD COLUMN IF NOT EXISTS take_profit_pct   NUMERIC NOT NULL DEFAULT 0.04
    CONSTRAINT chk_take_profit_pct_positive CHECK (take_profit_pct > 0 AND take_profit_pct <= 1.00),
  ADD COLUMN IF NOT EXISTS max_trade_size_usd NUMERIC NOT NULL DEFAULT 50.00
    CONSTRAINT chk_max_trade_size_positive CHECK (max_trade_size_usd > 0);

-- ---------------------------------------------------------------------------
-- 4. AUDIT LOG: Add trading-specific event types to security_audit_log
--    New columns: event_category (for filtering), severity_level
-- ---------------------------------------------------------------------------
ALTER TABLE public.security_audit_log
  ADD COLUMN IF NOT EXISTS event_category TEXT NOT NULL DEFAULT 'security',
  ADD COLUMN IF NOT EXISTS severity_level TEXT NOT NULL DEFAULT 'info'
    CONSTRAINT chk_severity_level CHECK (severity_level IN ('debug', 'info', 'warning', 'critical'));

-- Index for efficient audit log queries by category and severity
CREATE INDEX IF NOT EXISTS idx_security_audit_log_category
  ON public.security_audit_log (user_id, event_category, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_security_audit_log_severity
  ON public.security_audit_log (severity_level, created_at DESC)
  WHERE severity_level IN ('warning', 'critical');

-- ---------------------------------------------------------------------------
-- 5. KILL SWITCH TRIGGER: Automatically set paused_at when is_paused is set
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_paused_at()
RETURNS TRIGGER AS $$
BEGIN
  -- When is_paused transitions from false → true, record the timestamp
  IF NEW.is_paused = true AND (OLD.is_paused = false OR OLD.is_paused IS NULL) THEN
    NEW.paused_at := now();
  END IF;
  -- When is_paused transitions from true → false, clear the pause metadata
  IF NEW.is_paused = false AND OLD.is_paused = true THEN
    NEW.paused_at := NULL;
    NEW.paused_reason := NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_paused_at ON public.bot_config;
CREATE TRIGGER trg_set_paused_at
  BEFORE UPDATE ON public.bot_config
  FOR EACH ROW
  EXECUTE FUNCTION public.set_paused_at();

-- ---------------------------------------------------------------------------
-- 6. RLS: Ensure users can update their own is_paused (emergency stop from UI)
--    Service role can also update (for automated circuit breaker)
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "Users can update their own bot config" ON public.bot_config;

CREATE POLICY "Users can update their own bot config"
ON public.bot_config
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
