-- Migration: daily_reports — persisted daily trading summary per user

CREATE TABLE IF NOT EXISTS public.daily_reports (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date                DATE        NOT NULL,
  starting_balance    NUMERIC     NOT NULL DEFAULT 0,
  ending_balance      NUMERIC     NOT NULL DEFAULT 0,
  realized_pnl        NUMERIC     NOT NULL DEFAULT 0,
  unrealized_pnl      NUMERIC     NOT NULL DEFAULT 0,
  total_pnl           NUMERIC     NOT NULL DEFAULT 0,
  total_trades        INTEGER     NOT NULL DEFAULT 0,
  winning_trades      INTEGER     NOT NULL DEFAULT 0,
  losing_trades       INTEGER     NOT NULL DEFAULT 0,
  win_rate            NUMERIC     NOT NULL DEFAULT 0 CHECK (win_rate >= 0 AND win_rate <= 100),
  max_drawdown        NUMERIC     NOT NULL DEFAULT 0,
  open_positions_count INTEGER    NOT NULL DEFAULT 0,
  risk_events_count   INTEGER     NOT NULL DEFAULT 0,
  incidents_count     INTEGER     NOT NULL DEFAULT 0,
  current_mode        TEXT        NOT NULL DEFAULT 'paper' CHECK (current_mode IN ('paper', 'live')),
  bot_active_state    BOOLEAN     NOT NULL DEFAULT false,
  generated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT daily_reports_user_date_unique UNIQUE (user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_reports_user_id  ON public.daily_reports (user_id);
CREATE INDEX IF NOT EXISTS idx_daily_reports_date     ON public.daily_reports (date DESC);

ALTER TABLE public.daily_reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'daily_reports' AND policyname = 'Users can view their own daily reports'
  ) THEN
    CREATE POLICY "Users can view their own daily reports"
      ON public.daily_reports FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'daily_reports' AND policyname = 'Service role can insert daily reports'
  ) THEN
    CREATE POLICY "Service role can insert daily reports"
      ON public.daily_reports FOR INSERT
      WITH CHECK (auth.role() = 'service_role' OR auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'daily_reports' AND policyname = 'Service role can update daily reports'
  ) THEN
    CREATE POLICY "Service role can update daily reports"
      ON public.daily_reports FOR UPDATE
      USING  (auth.role() = 'service_role' OR auth.uid() = user_id)
      WITH CHECK (auth.role() = 'service_role' OR auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'daily_reports' AND policyname = 'Service role can delete daily reports'
  ) THEN
    CREATE POLICY "Service role can delete daily reports"
      ON public.daily_reports FOR DELETE
      USING (auth.role() = 'service_role');
  END IF;
END $$;

COMMENT ON TABLE public.daily_reports IS 'Persisted daily trading summary generated by notification-engine';
