// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxcbnkpflgecqreegdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeGNibmtwZmxnZWNxcmVlZ2RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTAwMzYsImV4cCI6MjA2OTQ2NjAzNn0.VoJYoXlzUSP992ldO3njrjyADxycDptUb1CHKfuNaJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});